USE ROLE ACCOUNTADMIN;

-- ------------------------------------------------------------------------------------------------------------------------ --
-- 3. SETUP ROLES --
-- ------------------------------------------------------------------------------------------------------------------------ --
  
CREATE OR REPLACE ROLE ROLE_HOL_LAB_DATASCIENCE;
GRANT OWNERSHIP ON DATABASE HOL_LAB_DATASCIENCE TO ROLE ROLE_HOL_LAB_DATASCIENCE;

GRANT USAGE ON WAREHOUSE WH_1_HOL_LAB_DATASCIENCE TO ROLE ROLE_HOL_LAB_DATASCIENCE;
GRANT OPERATE ON WAREHOUSE WH_1_HOL_LAB_DATASCIENCE TO ROLE ROLE_HOL_LAB_DATASCIENCE;

GRANT USAGE ON WAREHOUSE WH_2_HOL_LAB_DATASCIENCE TO ROLE ROLE_HOL_LAB_DATASCIENCE;
GRANT OPERATE ON WAREHOUSE WH_2_HOL_LAB_DATASCIENCE TO ROLE ROLE_HOL_LAB_DATASCIENCE;

GRANT USAGE ON WAREHOUSE WH_3_HOL_LAB_DATASCIENCE TO ROLE ROLE_HOL_LAB_DATASCIENCE;
GRANT OPERATE ON WAREHOUSE WH_3_HOL_LAB_DATASCIENCE TO ROLE ROLE_HOL_LAB_DATASCIENCE;

GRANT USAGE ON WAREHOUSE WH_4_HOL_LAB_DATASCIENCE TO ROLE ROLE_HOL_LAB_DATASCIENCE;
GRANT OPERATE ON WAREHOUSE WH_4_HOL_LAB_DATASCIENCE TO ROLE ROLE_HOL_LAB_DATASCIENCE;

GRANT CREATE NOTEBOOK ON FUTURE SCHEMAS IN DATABASE HOL_LAB_DATASCIENCE TO ROLE ROLE_HOL_LAB_DATASCIENCE;
GRANT CREATE STREAMLIT ON FUTURE SCHEMAS IN DATABASE HOL_LAB_DATASCIENCE TO ROLE ROLE_HOL_LAB_DATASCIENCE;
GRANT CREATE MODEL ON FUTURE SCHEMAS IN DATABASE HOL_LAB_DATASCIENCE TO ROLE ROLE_HOL_LAB_DATASCIENCE;
GRANT ROLE ROLE_HOL_LAB_DATASCIENCE TO ROLE SYSADMIN;

-- User assignment.
GRANT ROLE ROLE_HOL_LAB_DATASCIENCE TO CURRENT_USER();