USE ROLE ACCOUNTADMIN;
USE DATABASE HOL_LAB_DATASCIENCE;
USE SCHEMA LAB;

CREATE AUTHENTICATION POLICY require_mfa_with_password_authentication_policy
MFA_AUTHENTICATION_METHODS = ('PASSWORD')
MFA_ENROLLMENT = OPTIONAL;

ALTER ACCOUNT SET AUTHENTICATION POLICY require_mfa_with_password_authentication_policy; 