USE ROLE ACCOUNTADMIN;

-- Drop warehouses first (since they might be in use)
DROP WAREHOUSE IF EXISTS WH_1_HOL_LAB_DATASCIENCE;
DROP WAREHOUSE IF EXISTS WH_2_HOL_LAB_DATASCIENCE;
DROP WAREHOUSE IF EXISTS WH_3_HOL_LAB_DATASCIENCE;
DROP WAREHOUSE IF EXISTS WH_4_HOL_LAB_DATASCIENCE;

-- Drop database (this will cascade drop all schemas and objects within)
DROP DATABASE IF EXISTS HOL_LAB_DATASCIENCE; 