USE ROLE ACCOUNTADMIN;

-- Revoke role from users first
REVOKE ROLE ROLE_HOL_LAB_DATASCIENCE FROM CURRENT_USER();

-- Revoke role from SYSADMIN
REVOKE ROLE ROLE_HOL_LAB_DATASCIENCE FROM ROLE SYSADMIN;

-- Drop the role
DROP ROLE IF EXISTS ROLE_HOL_LAB_DATASCIENCE; 